spring:
  application:
    name: razorpay

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/razorpayDB}
    username: ${DB_USER}
    password: ${DB_PASS}
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: ${KAFKA_BROKERS:localhost:29092}
    producer:
      acks: all
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        enable.idempotence: true
        max.in.flight.request.per.connection: 5
        retries: 3
        spring.json.add.type.headers: false
    consumer:
      group-id: payflow-monolith
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDserializer
      properties:
        spring.json.trusted.package: "com.project.payflow.*"
        spring.json.use.type.headers: false
        spring.json.value.default.type: java.util.LinkedHashMap

DB_USER: postgres
DB_PASS: deepak123

vault:
  master-key: k5D8OqV+M7Qv9H0gW1xXx7vN2TzF6pL4sJ8cY2mRaEk=

payment:
  simulator:
    poll-interval-ms: 5000
    chaos-mode: NORMAL
    method:
      CARD:
        min-delay-seconds: 2
        max-delay-seconds: 6
        success-rate: 90
      UPI:
        min-delay-seconds: 1
        max-delay-seconds: 3
        success-rate: 95
      NET_BANKING:
        min-delay-seconds: 4
        max-delay-seconds: 10
        success-rate: 80

jwt:
  secret-key: sjihrjhsguusgkgju549ahfj;jawjiquaHJJJGUjJiohugvLJNDV;KJPUgSJGIHSUH

app:
  rate-limit:
    method: fixed
    use-case:
      api-key:
        request-per-minute: 2
  kafka:
    topics:
      payment: payments.events
      order: orders.events
      refund: refund.events
      settlement: settlement.events